//1
SELECT MOV_TITLE FROM MOVIE WHERE MOV_YEAR>=1990 AND MOV_YEAR<=2000;
//2
SELECT ACT_FIRSTNAME FROM ACTOR WHERE ACT_FIRSTNAME LIKE '%k' OR ACT_FIRSTNAME LIKE 'a%' OR ACT_FIRSTNAME LIKE '%a%' OR ACT_FIRSTNAME LIKE '%a';
//3
SELECT ACT_FIRSTNAME FROM ACTOR NATURAL JOIN DIRECTOR WHERE ACTOR.ACT_FIRSTNAME=DIRECTOR.DIR_FIRSTNAME;
//4
SELECT A.ACT_FIRSTNAME FROM ACTOR A, ACTOR B WHERE A.ACT_FIRSTNAME=B.ACT_FIRSTNAME AND A.ACT_ID!=B.ACT_ID;
//5
SELECT MOV_TITLE FROM MOVIE LEFT JOIN RATING WHERE RATING.REV_STARS=NULL;
//6
SELECT avg(REV_STARS) FROM RATING;
//7
SELECT count(MOV_COUNTRY), MOV_COUNTRY FROM MOVIE GROUP BY MOV_COUNTRY;
//8
SELECT min(REV_STARS),MOV_ID FROM RATING GROUP BY MOV_ID ORDER BY min(REV_STARS) DESC;
//9
SELECT M.MOV_TITLE FROM MOVIE M WHERE 
	( SELECT avg(REV_STARS) FROM RATING WHERE REV_STARS IS NOT NULL) <
	( SELECT avg(REV_STARS) FROM RATING R WHERE R.MOV_ID=M.MOV_ID AND R.REV_STARS IS NOT NULL)
	AND M.MOV_ID IN (SELECT MOV_ID FROM RATING);
//SELECT max(A_REV) FROM (SELECT avg(REV_STARS)  AS A_REV FROM RATING GROUP BY MOV_ID) A;
//10
SELECT A.ACT_FIRSTNAME AS ACT_NAME,
	(SELECT sum(R.REV_STARS) FROM RATING R WHERE R.MOV_ID IN
		(SELECT C.MOV_ID FROM CASTS C WHERE C.ACT_ID=A.ACT_ID))
	AS SUM_RATING FROM ACTOR A WHERE A.ACT_ID IN
	(SELECT C2.ACT_ID FROM CASTS C2 WHERE C2.MOV_ID IN
		(SELECT MOV_ID FROM RATING))
	ORDER BY SUM_RATING DESC;

//11
SELECT DIR_NAME, AVG_RATING FROM
(	SELECT D.DIR_FIRSTNAME AS DIR_NAME,
	(SELECT avg(R.REV_STARS) FROM RATING R WHERE R.MOV_ID IN
	( SELECT DN.MOV_ID FROM DIRECTION DN WHERE DN.DIR_ID=D.DIR_ID)
	AND R.REV_STARS IS NOT NULL)
	AS AVG_RATING
	FROM DIRECTOR D WHERE DIR_ID IN
	( SELECT DIR_ID FROM DIRECTION DN2 WHERE DN2.MOV_ID IN
	( SELECT MOV_ID FROM RATING))
	ORDER BY AVG_RATING DESC
)
WHERE ROWNUM = 1;
//12
SELECT * FROM MOVIE WHERE MOV_ID IN
	(SELECT DN.MOV_ID FROM DIRECTION DN WHERE DN.DIR_ID IN
	(SELECT D.DIR_ID FROM DIRECTOR D WHERE D.DIR_FIRSTNAME IN
 	(SELECT D1.DIR_FIRSTNAME FROM DIRECTOR D1
 	INTERSECT
 	SELECT A.ACT_FIRSTNAME FROM ACTOR A)));
//13
SELECT M.MOV_TITLE, ( SELECT avg(REV_STARS) FROM RATING R WHERE R.MOV_ID=M.MOV_ID AND REV_STARS IS NOT NULL) AS AVG_RATE
FROM MOVIE M WHERE M.MOV_ID IN 
	(SELECT RR.MOV_ID FROM RATING RR WHERE RR.REV_STARS IS NOT NULL
	 GROUP BY RR.MOV_ID HAVING avg(RR.REV_STARS) > 7 ) 
ORDER BY AVG_RATE DESC;
//14
SELECT R.REV_NAME FROM REVIEWER R WHERE R.REV_ID IN
(SELECT RT.REV_ID FROM RATING RT WHERE RT.REV_STARS =( SELECT min (REV_STARS) FROM RATING));
//
//9
SELECT M.MOV_TITLE FROM MOVIE M
WHERE M.MOV_ID IN (
	SELECT MOV_ID
	FROM RATING
	WHERE REV_STARS IS NOT NULL
	GROUP BY MOV_ID
	HAVING AVG(REV_STARS) < (
		SELECT AVG(REV_STARS)
		FROM RATING
	)
);
//10
SELECT A.ACT_FIRSTNAME, CR.AVG_STARS
FROM ACTOR A, (SELECT C.ACT_ID, RR.AVG_STARS
FROM CASTS C, (SELECT R.MOV_ID, COUNT(R.REV_STARS) AS AVG_STARS
FROM RATING R GROUP BY R.MOV_ID) RR
WHERE C.MOV_ID=RR.MOV_ID
) CR WHERE A.ACT_ID=CR.ACT_ID;