
SELECT C.CUSTOMER_NAME, C.CUSTOMER_CITY
FROM CUSTOMER C
JOIN BORROWER B ON B.CUSTOMER_NAME = C.CUSTOMER_NAME
LEFT JOIN DEPOSITOR D ON D.CUSTOMER_NAME = C.CUSTOMER_NAME
WHERE D.ACCOUNT_NUMBER IS NULL;

SELECT C.CUSTOMER_NAME, C.CUSTOMER_CITY FROM CUSTOMER C WHERE C.CUSTOMER_NAME IN
	(SELECT B.CUSTOMER_NAME FROM BORROWER B WHERE B.LOAN_NUMBER IS NOT NULL)
	AND C.CUSTOMER_NAME IN (SELECT D.CUSTOMER_NAME FROM DEPOSITOR D WHERE D.ACCOUNT_NUMBER IS NOT NULL);

SELECT EXTRACT(MONTH FROM (ACC_OPENING_DATE)) MONTH, COUNT(ACCOUNT_NUMBER) FROM ACCOUNT  
GROUP BY EXTRACT(MONTH FROM(ACC_OPENING_DATE));

SELECT MONTHS_BETWEEN(MAX(L.LOAN_DATE), MAX(AA.ACC_OPENING_DATE)) AS MONTHS_BETWEEN FROM 
(SELECT B.CUSTOMER_NAME, B.LOAN_NUMBER, A.ACC_OPENING_DATE FROM
(SELECT CUSTOMER_NAME, ACC_OPENING_DATE
FROM DEPOSITOR D, ACCOUNT A
WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER) A, BORROWER B
WHERE B.CUSTOMER_NAME='Smith' AND B.CUSTOMER_NAME=A.CUSTOMER_NAME) AA, LOAN L WHERE AA.LOAN_NUMBER=L.LOAN_NUMBER;

SELECT A.CUSTOMER_NAME,A.TOT_BALANCE FROM
(SELECT CUSTOMER_NAME, SUM(BALANCE) AS TOT_BALANCE
FROM DEPOSITOR D, ACCOUNT A
WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
GROUP BY CUSTOMER_NAME) A
WHERE A.TOT_BALANCE=(SELECT MAX(TOT_BALANCE)
FROM (SELECT CUSTOMER_NAME, SUM(BALANCE) AS TOT_BALANCE
FROM DEPOSITOR D, ACCOUNT A
WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
GROUP BY CUSTOMER_NAME));

SELECT DISTINCT BR.CUSTOMER_NAME || ' ELIGIBLE' FROM(
SELECT B.CUSTOMER_NAME, L.AMOUNT AS LOAN_VAL
FROM BORROWER B, LOAN L
WHERE L.LOAN_NUMBER=B.LOAN_NUMBER) TA,
(SELECT A.ACCOUNT_NUMBER, SUM(A.BALANCE) AS TOT_BALANCE
FROM DEPOSITOR D, ACCOUNT A
WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
GROUP BY A.ACCOUNT_NUMBER) TB, DEPOSITOR BR
WHERE TB.TOT_BALANCE>=TA.LOAN_VAL AND TB.ACCOUNT_NUMBER=BR.ACCOUNT_NUMBER AND BR.CUSTOMER_NAME=TA.CUSTOMER_NAME;

SELECT CUSTOMER_NAME ||' Elite' FROM(
SELECT CUSTOMER_NAME, SUM(BALANCE) AS TOT_BALANCE
FROM DEPOSITOR D, ACCOUNT A
WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
GROUP BY CUSTOMER_NAME) A, 
(SELECT AVG(BALANCE) AS AVG_BALANCE
FROM ACCOUNT A) B
WHERE A.TOT_BALANCE> B.AVG_BALANCE+500;

SELECT CUSTOMER_NAME ||' Moderate' FROM(
SELECT CUSTOMER_NAME, SUM(BALANCE) AS TOT_BALANCE
FROM DEPOSITOR D, ACCOUNT A
WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
GROUP BY CUSTOMER_NAME) A, 
(SELECT AVG(BALANCE) AS AVG_BALANCE
FROM ACCOUNT A) B
WHERE A.TOT_BALANCE<= B.AVG_BALANCE+500 AND A.TOT_BALANCE>=B.AVG_BALANCE-500;

SELECT CUSTOMER_NAME ||' Poor' FROM(
SELECT CUSTOMER_NAME, SUM(BALANCE) AS TOT_BALANCE
FROM DEPOSITOR D, ACCOUNT A
WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
GROUP BY CUSTOMER_NAME) A, 
(SELECT AVG(BALANCE) AS AVG_BALANCE
FROM ACCOUNT A) B
WHERE A.TOT_BALANCE< B.AVG_BALANCE-500;

SELECT DISTINCT B.BRANCH_NAME, B.BRANCH_CITY, B.ASSETS
FROM CUSTOMER C, BRANCH B
WHERE C.CUSTOMER_NAME NOT IN
(SELECT D.CUSTOMER_NAME
FROM DEPOSITOR D, ACCOUNT A
WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER) AND 
C.CUSTOMER_CITY=B.BRANCH_CITY;

DROP TABLE NEW_CUSTOMER;
CREATE TABLE NEW_CUSTOMER AS SELECT * FROM CUSTOMER WHERE 1=2;

INSERT INTO NEW_CUSTOMER
(SELECT DISTINCT C.CUSTOMER_NAME, C.CUSTOMER_STREET, C.CUSTOMER_CITY
FROM CUSTOMER C, (SELECT CUSTOMER_NAME 
		FROM DEPOSITOR WHERE ACCOUNT_NUMBER IS NOT NULL) D,
		(SELECT CUSTOMER_NAME
		FROM BORROWER WHERE LOAN_NUMBER IS NOT NULL) B
WHERE C.CUSTOMER_NAME=D.CUSTOMER_NAME OR C.CUSTOMER_NAME=B.CUSTOMER_NAME);

ALTER TABLE NEW_CUSTOMER ADD STATUS VARCHAR2(15);

UPDATE NEW_CUSTOMER
SET STATUS = CASE
WHEN
	CUSTOMER_NAME IN
	(SELECT DISTINCT TA.CUSTOMER_NAME 
	FROM
	(SELECT SUM(A.BALANCE) AS BAL, D.CUSTOMER_NAME
	FROM DEPOSITOR D, ACCOUNT A 
	WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
	GROUP BY D.CUSTOMER_NAME) TA, 
	(SELECT SUM(L.AMOUNT) AS LO, B.CUSTOMER_NAME
	FROM BORROWER B, LOAN L 
	WHERE B.LOAN_NUMBER=L.LOAN_NUMBER
	GROUP BY B.CUSTOMER_NAME) TB
	WHERE TA.BAL>TB.LO AND TA.CUSTOMER_NAME=TB.CUSTOMER_NAME) 
	THEN 'In Savings'
WHEN
	CUSTOMER_NAME IN
	(SELECT DISTINCT TA.CUSTOMER_NAME 
	FROM
	(SELECT SUM(A.BALANCE) AS BAL, D.CUSTOMER_NAME
	FROM DEPOSITOR D, ACCOUNT A 
	WHERE D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
	GROUP BY D.CUSTOMER_NAME) TA, 
	(SELECT SUM(L.AMOUNT) AS LO, B.CUSTOMER_NAME
	FROM BORROWER B, LOAN L 
	WHERE B.LOAN_NUMBER=L.LOAN_NUMBER
	GROUP BY B.CUSTOMER_NAME) TB
	WHERE TA.BAL<TB.LO AND TA.CUSTOMER_NAME=TB.CUSTOMER_NAME) 
	THEN 'In Loan'
ELSE 
	'In Breakeven'
END;
SELECT * FROM NEW_CUSTOMER;