//1
CREATE VIEW Advisor_Selection AS
	SELECT ID, NAME, DEPT_NAME
	FROM INSTRUCTOR;
//2.
CREATE VIEW Student_Count AS
	(SELECT I.NAME, A.ST_COU
	FROM
	(SELECT I_ID, COUNT(S_ID) AS ST_COU
	FROM ADVISOR
	GROUP BY I_ID) A JOIN INSTRUCTOR I
	ON I.ID=A.I_ID);
//3a
CREATE ROLE ST_ROLE;
GRANT SELECT ON moushi.ADVISOR TO ST_ROLE;
GRANT SELECT ON moushi.COURSE TO ST_ROLE;
//3b
CREATE ROLE T_ROLE;
GRANT SELECT ON moushi.STUDENT TO T_ROLE;
GRANT SELECT ON moushi.COURSE TO T_ROLE;
//3c
CREATE ROLE HEAD;
GRANT T_ROLE TO HEAD;
GRANT INSERT ON moushi.INSTRUCTOR TO HEAD;
//3d
CREATE ROLE ADMIN;
GRANT SELECT ON moushi.DEPARTMENT TO ADMIN;
GRANT SELECT ON moushi.INSTRUCTOR TO ADMIN;
GRANT UPDATE ON moushi.DEPARTMENT TO ADMIN;
//4
CREATE USER STUDENT1 IDENTIFIED BY 123;
GRANT ST_ROLE TO STUDENT1;
GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO STUDENT1;
CREATE USER TEACHER1 IDENTIFIED BY 123;
GRANT T_ROLE TO TEACHER1;
GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO TEACHER1;
CREATE USER DEPT_H IDENTIFIED BY 123;
GRANT HEAD TO DEPT_H;
GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO DEPT_H;
CREATE USER AD IDENTIFIED BY 123;
GRANT ADMIN TO AD;
GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO AD;

connect STUDENT1/123
SELECT * FROM moushi.ADVISOR NATURAL JOIN moushi.COURSE;

connect teacher1/123
SELECT * FROM moushi.STUDENT;

connect DEPT_H/123
INSERT INTO moushi.INSTRUCTOR VALUES ('3455', 'DF', 'Biology', 45556);

connect ad/123
UPDATE moushi.DEPARTMENT SET BUDGET='500' WHERE DEPT_NAME='Biology';
